Repository DevelopingSpace/starchart, pull requests merged in 2023-02, with the labels that each got.

#73 Update README
  README.md
  img/Starchart architecture.drawio.png
Labels: documentation

#93 Add middleware from Satellite
  app/lib/logger.server.ts
  package-lock.json
  package.json
  server.ts
Labels: enhancement, back-end

#125 Configure Nodemailer transport with OAuth2
  app/lib/notifications.server.ts
  package-lock.json
  package.json
Labels: back-end, notifications

#133 Dependabot: ignore major updates
  .github/dependabot.yml
Labels: dependencies

#144 Bump version to 0.1.0 in package.json
  package.json
Labels: documentation

#146 Setup MailHog in Docker to send test notifications
  .env.example
  app/lib/notifications.server.ts
  docker-compose.yml
Labels: back-end, notifications

#152 Update Nodemailer production transport options for testing
  app/lib/notifications.server.ts
  package-lock.json
  package.json
Labels: tests, back-end, notifications

#166 Header & Login - UI Implementation
  app/components/header.tsx
  app/routes/__index/index.tsx
  app/routes/login.tsx
  package-lock.json
  package.json
Labels: front-end

#188 chore: add docker and github actions to Dependabot config
  .github/dependabot.yml
Labels: dependencies

#181 Add domain table to domains list page
  app/components/domains-table.tsx
  app/mocks/domains.ts
  app/routes/__index/domains/index.tsx
Labels: front-end

#216 feat: Add Redis for testing
  .github/workflows/ci.yaml
Labels: category: testing, category: containers

#207 Feat: add button on domains page
  app/routes/__index/domains/index.tsx
Labels: category: front end

#140 Updated architecture with new areas
  img/Starchart architecture.drawio.png
Labels: category: documentation

#212 Making header responsive
  app/components/header.tsx
Labels: category: front end

#224 chore: fix Dependabot version updates bug and fix labels
  .github/dependabot.yml
Labels: dependencies

#214 feat: ACME flow skeleton
  app/queues/certificate/certificate-flow.server.ts
  app/queues/certificate/challenge-completer-worker.server.ts
  app/queues/certificate/dns-cleaner-worker.server.ts
  app/queues/certificate/dns-waiter-worker.server.ts
  app/queues/certificate/order-completer-worker.server.ts
  app/queues/certificate/order-creator-worker.server.ts
  app/queues/notifications.server.ts
  app/routes/dev.tsx
  server.ts
Labels: category: certificates, category: queue

#184 Add unit tests for Nodemailer
  .github/workflows/ci.yaml
  package.json
  test/unit/notifications.server.test.ts
Labels: category: testing, category: back end, category: notifications

#231 Build Docker image for linux/amd64, linux/arm64, and linux/arm64/v8
  .github/workflows/ci.yaml
Labels: category: deployment, category: containers

#234 Remove docker platforms from CI
  .github/workflows/ci.yaml
Labels: category: deployment, category: containers

#235 Use shared redis connection in FlowProducer
  app/queues/certificate/certificate-flow.server.ts
Labels: category: queue

#223 Specify a nonce for all scripts
  app/root.tsx
  server.ts
Labels: category: front end, category: back end

#228 Add CRUD functions for models via Prisma
  app/models/certificate.server.ts
  app/models/challenge.server.ts
  app/models/record.server.ts
  app/models/user.server.ts
Labels: category: data

#233 Improve domain name validation
  app/lib/dns.server.ts
  app/lib/domains.server.ts
  package-lock.json
  package.json
  test/unit/dns.server.test.ts
  test/unit/domains.server.test.ts
Labels: category: DNS, category: data

#232 Implement UI for certificate
  app/components/certificate/certificate-available.tsx
  app/components/certificate/certificate-display.tsx
  app/components/certificate/certificate-request.tsx
  app/components/certificate/description.tsx
  app/components/certificate/loading.tsx
  app/routes/__index/certificate/index.tsx
  img/LICENSE
  img/undraw_processing_re_tbdu.svg
Labels: category: front end, area: web

#254 Use Docker Secrets in dev and production
  .dockerignore
  .env.example
  .eslintignore
  .prettierignore
  CONTRIBUTING.md
  app/lib/dns.server.ts
  app/lib/lets-encrypt.server.ts
  app/lib/notifications.server.ts
  app/lib/secrets.server.ts
  app/session.server.ts
  dev-secrets/AWS_ACCESS_KEY_ID
  dev-secrets/AWS_SECRET_ACCESS_KEY
  dev-secrets/DATABASE_URL
  dev-secrets/LETS_ENCRYPT_ACCOUNT_PRIVATE_KEY_PEM
  dev-secrets/NOTIFICATIONS_PASSWORD
  dev-secrets/NOTIFICATIONS_USERNAME
  dev-secrets/SESSION_SECRET
  package.json
Labels: category: deployment, category: containers, dependency: docker

#263 Remove unnecessary ioredis types stub
  package-lock.json
  package.json
Labels: dependencies

#264 Add DEPLOY.md with initial config info, s/MAILHOG_SMTP_PORT/SMTP_PORT/
  .env.example
  DEPLOY.md
  LICENSE
  README.md
  app/lib/notifications.server.ts
Labels: category: documentation, category: deployment

#236 #195 SSO and SLO additions
  .env.example
  CONTRIBUTING.md
  app/routes/login.tsx
  app/routes/login/callback.tsx
  app/routes/logout.tsx
  app/routes/logout/callback.tsx
  app/routes/sp.tsx
  app/saml.server.ts
  config/saml20-idp-hosted.php
  dev-secrets/SAML_IDP_METADATA
  docker-compose.yml
  package-lock.json
  package.json
Labels: category: authentication

#256 Making Certificate UI responsive
  app/components/certificate/certificate-available.tsx
  app/components/certificate/certificate-display.tsx
  app/components/certificate/certificate-request.tsx
  app/components/certificate/description.tsx
  app/components/certificate/loading.tsx
  app/components/header.tsx
  app/routes/__index/certificate/index.tsx
  app/theme/breakpoints.ts
  app/theme/index.ts
Labels: enhancement, category: front end, area: web
