Repository DevelopingSpace/starchart, pull requests merged in 2023-04, with the labels that each got.

#483 Tests for functions that interact with system state
  app/models/system-state.server.ts
  test/unit/system-state.server.test.ts
Labels: category: testing

#451 Create admin page with layout
  app/components/admin/admin-metric-card.tsx
  app/components/admin/users-table.tsx
  app/models/certificate.server.ts
  app/models/dns-record.server.ts
  app/models/user.server.ts
  app/routes/__index/admin/index.tsx
Labels: category: front end, area: web

#458 Configure auto-removal of jobs on completion/failure
  .env.example
  DEPLOY.md
  app/queues/certificate/certificate-flow.server.ts
  app/queues/common/expiration-request.server.ts
  app/queues/notifications/notifications.server.ts
  app/queues/reconciler/reconciler-queue.server.ts
Labels: category: back end, category: queue

#487 Add checks for deactivated users
  app/models/dns-record.server.ts
  app/models/user.server.ts
  app/queues/certificate/certificate-flow.server.ts
  app/queues/certificate/challenge-completer-worker.server.ts
  app/queues/certificate/dns-waiter-worker.server.ts
  app/queues/certificate/order-completer-worker.server.ts
  app/queues/certificate/order-creator-worker.server.ts
  app/session.server.ts
  test/unit/user.server.test.ts
Labels: category: certificates, new feature, category: DNS, category: authentication

#474 FE: Download Icon Functional
  app/components/certificate/certificate-available.tsx
  app/components/certificate/certificate-display.tsx
  app/routes/__index/certificate/cert.ts
  app/routes/__index/certificate/privkey.ts
Labels: category: front end, area: web

#497 Bug: fix issue with pending page not displaying
  app/models/certificate.server.ts
Labels: category: front end

#503 Update avatar colour
  app/components/header.tsx
Labels: category: front end

#504 Make DNS Record form text more helpful
  app/components/dns-record/form-field.tsx
  app/components/dns-record/form.tsx
  app/theme/index.ts
  test/e2e/new-dns-record.spec.ts
Labels: category: front end

#509 Add record count in dns record table
  app/routes/__index/dns-records/index.tsx
Labels: category: front end

#510 Send notification when certificate completion succeeds
  app/models/certificate.server.ts
  app/queues/certificate/order-completer-worker.server.ts
Labels: category: certificates, category: notifications

#521 Adding a message when certificate failed
  app/components/certificate/certificate-request.tsx
  app/routes/__index/certificate/index.tsx
Labels: category: front end, area: web

#514 Replace placeholder text
  app/components/certificate/certificate-available.tsx
  app/components/certificate/certificate-request.tsx
  app/components/landing-page/landing-page-card.tsx
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/index.tsx
  app/routes/__index/dns-records/new.tsx
  app/routes/__index/index.tsx
  test/e2e/landing-page.spec.ts
  test/e2e/login.spec.ts
Labels: category: front end

#512 Use journald log driver, update DEPLOY docs on logging
  DEPLOY.md
  docker-compose.yml
  docker-production.yml
  docker-staging.yml
Labels: category: deployment

#529 Connect Admin UI to landing page
  app/components/landing-page/landing-page-card.tsx
  app/routes/__index/index.tsx
  test/e2e/landing-page.spec.ts
Labels: category: front end

#530 Add separate Certificate Views for different use cases/services
  app/components/certificate/certificate-available.tsx
  app/components/certificate/panels/aws.tsx
  app/components/certificate/panels/general.tsx
  app/components/certificate/panels/node.tsx
  app/routes/__index/certificate/index.tsx
Labels: category: front end

#531 Add admin login setup for e2e tests
  test/e2e/auth.setup.ts
  test/e2e/utils.ts
Labels: category: testing

#534 Add an info button linking to DNSChecker
  app/components/dns-records-table.tsx
Labels: category: front end

#544 Make links more obvious
  app/components/certificate/panels/aws.tsx
  app/components/landing-page/landing-page-card.tsx
  app/routes/__index/index.tsx
  app/theme/index.ts
Labels: category: front end, area: web

#542 Prevent duplicate CNAME for a user
  app/models/dns-record.server.ts
Labels: category: DNS, category: data

#533 Enhc: Adding the ability to request for new certificate
  app/components/certificate/certificate-available.tsx
  app/components/certificate/description.tsx
  app/models/certificate.server.ts
  app/routes/__index/certificate/index.tsx
Labels: category: front end, area: web

#541 Wrap components with body layout
  app/components/admin/admin-metric-card.tsx
  app/components/certificate/certificate-available.tsx
  app/components/certificate/certificate-request.tsx
  app/components/certificate/description.tsx
  app/routes/__index.tsx
  app/routes/__index/admin/index.tsx
  app/routes/__index/certificate/index.tsx
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/index.tsx
  app/routes/__index/dns-records/new.tsx
  test/e2e/login.spec.ts
Labels: category: front end

#540 process certificate expiration
  app/models/certificate.server.ts
  app/queues/common/expiration-request.server.ts
Labels: category: certificates, category: notifications

#552 Add label to 'renew' button
  app/components/certificate/description.tsx
Labels: category: front end

#561 Make 'Renew' button responsive
  app/components/certificate/description.tsx
Labels: category: front end, area: web

#545 Add dns record instruction page
  app/components/instructions/faq-accordion.tsx
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/index.tsx
  app/routes/__index/dns-records/instructions.tsx
  app/routes/__index/dns-records/new.tsx
Labels: category: front end, area: web

#565 Adding Certificate Instruction Page
  app/components/certificate/certificate-request.tsx
  app/components/certificate/description.tsx
  app/components/landing-page/landing-page-card.tsx
  app/routes/__index/certificate/information.tsx
  app/routes/__index/certificate/instructions.tsx
  app/routes/__index/dns-records/instructions.tsx
  app/routes/__index/index.tsx
  test/e2e/landing-page.spec.ts
Labels: category: front end

#578 Tidy up seed file
  prisma/seed.ts
Labels: area: devOps

#570 Sort user records in model
  app/models/dns-record.server.ts
Labels: category: data

#583 Replace doesDnsRecordExist with isDuplicateCname
  app/models/dns-record.server.ts
Labels: category: data

#612 Renew DNS Records: Always Clickable
  app/components/dns-record-table-row.tsx
Labels: category: front end

#608 Improve instructions link on DNS record page, form and DNS record Id
  app/components/landing-page/landing-page-card.tsx
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/index.tsx
  app/routes/__index/dns-records/new.tsx
  test/e2e/landing-page.spec.ts
Labels: category: front end

#607 Add user deactivation functionality
  app/components/admin/users-table.tsx
  app/lib/user.server.ts
  app/routes/__index/admin/index.tsx
Labels: category: back end, area: web

#617 Open external links in new tab
  app/routes/__index/certificate/information.tsx
  app/routes/__index/index.tsx
Labels: category: front end

#566 Restructure expiration notification worker code
  services/expiration/expiration-notification.server.ts
Labels: category: certificates, category: notifications

#624 Replace DNSChecker with NSLookup
  app/components/dns-record-table-row.tsx
Labels: bug, category: front end

#626 Add Clickable Functionality to Avatar and Username
  app/components/header.tsx
Labels: category: front end

#633 Remove Development heading from README.md
  README.md
Labels: category: documentation

#613 Update certificate UI test
  app/models/certificate.server.ts
  test/e2e/certificate-available.spec.ts
  test/e2e/certificate-request.spec.ts
  test/e2e/certificate.spec.ts
Labels: category: testing

#639 Rework default tags for staging and production builds
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  docker-production.yml
  docker-staging.yml
Labels: category: deployment

#627 Add "Alt" Text Attribute to Image
  app/components/image-with-message.tsx
  app/routes/_auth.certificate._index.tsx
Labels: category: front end

#641 Update deps for 1.0.0
  package-lock.json
  package.json
Labels: dependencies

#658 Add bottom padding in dns instruction
  app/routes/_auth.dns-records.instructions.tsx
Labels: category: front end

#628 Add minimal footer
  app/components/footer.tsx
  app/routes/_auth._index.tsx
  app/routes/_auth.tsx
Labels: category: front end, area: web

#659 Update certificate pending message
  app/components/image-with-message.tsx
  app/routes/_auth.certificate._index.tsx
Labels: category: front end

#662 Fix padding issue on 'new' dns record route
  app/components/certificate/certificate-display.tsx
  app/routes/_auth.dns-records.new.tsx
Labels: bug, category: front end, area: web

#676 Fix DNS record alignment issue
  app/components/dns-record-table-row.tsx
Labels: category: front end, area: web
