Repository DevelopingSpace/starchart, pull requests merged in 2023-03, with the labels that each got.

#274 Add dns work flows
  app/lib/dns.server.ts
  app/queues/dns/create-record-worker.server.ts
  app/queues/dns/dns-flow.server.ts
  app/routes/dev.tsx
  package.json
Labels: category: back end, category: DNS, category: queue, category: data

#283 Add server init logic for SAML and DNS
  .github/workflows/ci.yaml
  app/lib/dns.server.ts
  app/lib/saml.server.ts
  app/routes/login.tsx
  app/routes/login/callback.tsx
  app/routes/logout.tsx
  app/routes/sp.tsx
  app/saml.server.ts
  server.ts
Labels: category: back end

#310 Landing Page UI | Access Denied/Login Failed Page
  app/assets/undraw_server_down_s-4-lk.svg
  app/components/certificate/description.tsx
  app/components/display-page.tsx
  app/components/header.tsx
  app/components/landing-page/landing-page-card.tsx
  app/routes/__index/certificate/index.tsx
  app/routes/__index/domains/$domainId.tsx
  app/routes/__index/domains/index.tsx
  app/routes/__index/index.tsx
  test/e2e/login.spec.ts
Labels: category: front end, area: web

#268 Add Worker/Queues to process notification based on status
  app/lib/notifications.server.ts
  app/models/record.server.ts
  app/queues/notifications/expiration-notification.server.ts
  app/queues/notifications/notifications.server.ts
  app/routes/__index/certificate/index.tsx
  app/routes/dev.tsx
  prisma/schema.prisma
  prisma/seed.ts
  server.ts
Labels: category: notifications, area: functionality, category: queue

#322 fix: problems in notifications related code
  app/lib/notifications.server.ts
Labels: category: notifications

#327 Use secrets for DATABASE_URL in prod, update deploy docs
  DEPLOY.md
  app/db.server.ts
Labels: category: documentation, category: deployment

#325 Add prisma Docker target + CI to setup db in staging/prod
  .github/workflows/ci.yaml
  .npmrc
  DEPLOY.md
  Dockerfile
  docker-entrypoint.sh
Labels: category: deployment, category: containers

#335 Fixes to Dockerfile for staging
  Dockerfile
Labels: category: deployment

#339 Use username and baseDomain in /certificate
  app/routes/__index/certificate/index.tsx
Labels: category: front end

#340 Retry playwright tests at least once
  playwright.config.ts
Labels: category: testing

#354 Add documentation about debugging e2e tests
  CONTRIBUTING.md
Labels: category: documentation, category: testing

#367 Add deactivated flag to users
  app/models/user.server.ts
  prisma/schema.prisma
  prisma/seed.ts
  test/unit/user.server.test.ts
Labels: category: back end, area: web, category: data

#357 Add Worker/Queue to process expired DNS records
  .env.example
  app/models/record.server.ts
  app/queues/common/expiration-request.server.ts
  app/queues/notifications/expiration-notification.server.ts
  app/queues/notifications/notifications.server.ts
Labels: category: notifications, category: DNS

#365 Test: Certificate, Header
  app/components/certificate/certificate-display.tsx
  app/components/header.tsx
  playwright.config.ts
  test/e2e/auth.setup.ts
  test/e2e/certificate.spec.ts
  test/e2e/header/header.desktop.spec.ts
  test/e2e/header/header.mobile.spec.ts
  test/e2e/header/header.spec.ts
  test/e2e/landing-page.spec.ts
  test/e2e/login.spec.ts
  test/e2e/new-dns-record.spec.ts
Labels: category: testing

#398 Add scripts for test database setup
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  app/db.server.ts
  package.json
Labels: category: testing, area: devOps

#397 refactor: use DnsRecord in code and DNS Record in UI text
  .env.example
  app/components/dns-record-delete-alert-dialog.tsx
  app/components/dns-record/form.tsx
  app/components/dns-records-table.tsx
  app/components/header.tsx
  app/lib/dns.server.ts
  app/models/dns-record.server.ts
  app/models/record.server.ts
  app/queues/certificate/order-creator-worker.server.ts
  app/queues/common/expiration-request.server.ts
  app/queues/dns/add-dns-record-flow.server.ts
  app/queues/dns/delete-dns-record-flow.server.ts
  app/queues/dns/update-dns-record-flow.server.ts
  app/queues/dns/workers/dns-update-worker.server.ts
  app/queues/dns/workers/sync-db-status-worker.server.ts
  app/queues/notifications/expiration-notification.server.ts
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/index.tsx
  app/routes/__index/dns-records/new.tsx
  app/routes/__index/index.tsx
  app/routes/dev.tsx
  app/theme/index.ts
  package-lock.json
  prisma/schema.prisma
  prisma/seed.ts
  test/e2e/header/header.desktop.spec.ts
  test/e2e/header/header.mobile.spec.ts
  test/e2e/landing-page.spec.ts
  test/e2e/login.spec.ts
  test/e2e/new-dns-record.spec.ts
  test/unit/dns.server.test.ts
Labels: category: front end, category: back end, area: web

#411 Bump @remix-run dependencies to 1.14.3
  package-lock.json
  package.json
Labels: dependencies

#417 Rename name to fqdn or subdomain
  app/lib/dns.server.ts
  app/queues/dns/workers/dns-update-worker.server.ts
Labels: category: DNS

#410 Update vitest config
  .gitignore
  package-lock.json
  package.json
  vitest.config.ts
Labels: category: testing, area: devOps

#415 Adding tests for functions relating to User model
  package.json
  test/unit/user.server.test.ts
Labels: category: testing, category: back end, category: data

#422 Improve race condition in npm run dev
  package.json
Labels: area: devOps

#421 Update playwright and add --ui script via e2e
  package-lock.json
  package.json
Labels: category: testing

#419 Refactor DNS away from flows, deal with errors
  app/components/dns-records-table.tsx
  app/lib/dns.server.ts
  app/queues/certificate/order-creator-worker.server.ts
  app/queues/common/expiration-request.server.ts
  app/queues/dns/add-dns-record-flow.server.ts
  app/queues/dns/delete-dns-record-flow.server.ts
  app/queues/dns/dns-queue.server.ts
  app/queues/dns/dns-worker.server.ts
  app/queues/dns/index.server.ts
  app/queues/dns/update-dns-record-flow.server.ts
  app/queues/dns/workers/dns-update-worker.server.ts
  app/queues/dns/workers/poll-dns-status-worker.server.ts
  app/queues/dns/workers/sync-db-status-worker.server.ts
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/index.tsx
  app/routes/__index/dns-records/new.tsx
  app/routes/dev.tsx
  test/unit/dns.server.test.ts
Labels: category: DNS

#424 Exclude acme challenge in user account
  app/models/dns-record.server.ts
Labels: category: DNS, category: data

#428 Add tooltip for optional DNS record info in table
  app/components/dns-record/dns-record-name.tsx
  app/components/dns-records-table.tsx
Labels: category: front end

#429 Hide table if no DNS Records exist
  app/routes/__index/dns-records/index.tsx
Labels: category: front end, area: web

#430 Improve landing page link accessibility
  app/components/landing-page/landing-page-card.tsx
  app/routes/__index/index.tsx
Labels: bug, category: front end, area: web

#431 Improve DNS record renew button usability
  app/components/dns-records-table.tsx
Labels: category: front end, area: web, category: DNS

#432 Fix html, body styling, update head
  app/root.tsx
  app/routes/login.tsx
  public/styles.css
Labels: category: front end, area: web

#400 Add webhook/ with webhook JSON config and deploy.sh with docs
  .github/workflows/ci.yaml
  DEPLOY.md
  webhook/README.md
  webhook/deploy.sh
  webhook/hooks.json
  webhook/starchart-webhook.service
Labels: category: deployment, area: devOps, dependency: docker

#412 Notify user when DNS record status change from `pending` to `active`/`error`
  app/models/dns-record.server.ts
  app/queues/dns/dns-queue.server.ts
Labels: category: back end, category: notifications, category: DNS

#456 Replacing Varchar to Text for 'privateKey' and 'certificate
  prisma/schema.prisma
Labels: category: data

#457 Fix DNS record expiry date always being set to July
  app/models/dns-record.server.ts
Labels: bug, category: back end

#449 Add bad word filter
  app/lib/dns.server.ts
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/new.tsx
  package-lock.json
  package.json
  test/unit/dns.server.test.ts
Labels: category: DNS

#464 Refactor to use database as DNS ground truth, remove DNS worker code
  app/components/dns-record/form.tsx
  app/components/dns-records-table.tsx
  app/lib/dns.server.ts
  app/models/dns-record.server.ts
  app/queues/certificate/order-creator-worker.server.ts
  app/queues/common/expiration-request.server.ts
  app/queues/dns/dns-queue.server.ts
  app/queues/dns/dns-worker.server.ts
  app/queues/dns/index.server.ts
  app/routes/__index/dns-records/$dnsRecordId.tsx
  app/routes/__index/dns-records/index.tsx
  app/routes/__index/dns-records/new.tsx
  app/routes/dev.tsx
  prisma/schema.prisma
  test/unit/dns.server.test.ts
Labels: category: DNS, category: data

#481 Update esbuild to fix crash introduced by PR #471
  package-lock.json
  package.json
Labels: bug

#434 Back-End Connection with Certificate UI
  app/components/certificate/certificate-request.tsx
  app/components/display-page.tsx
  app/models/certificate.server.ts
  app/routes/__index/certificate/index.tsx
  app/routes/__index/dns-records/instructions.tsx
  test/e2e/certificate.spec.ts
Labels: category: front end, area: web

#485 Create docker-production.yml similar to docker-staging.yml
  docker-production.yml
Labels: category: deployment

#484 Update DEPLOY info with more details
  DEPLOY.md
Labels: category: documentation, category: deployment

#492 FE: Adding Seneca Policy Link
  app/routes/__index/index.tsx
Labels: category: front end, area: web

#489 FE: Fixing the style of certificate text
  app/components/certificate/certificate-display.tsx
Labels: category: front end, area: web
